Simplify usage of stack-haddock-upload

diff --git a/stack-haddock-upload b/stack-haddock-upload
--- a/stack-haddock-upload
+++ b/stack-haddock-upload
@@ -1,26 +1,28 @@
 #!/bin/bash
 
-# Author: Dimitri Sabadie <dimitri.sabadie@gmail.com>
-# 2015
+# Adapted from script by Dimitri Sabadie <dimitri.sabadie@gmail.com>
 
-dist=`stack path --dist-dir --stack-yaml ./stack.yaml 2> /dev/null`
+dist=$(stack path --dist-dir --stack-yaml ./stack.yaml)
+packagename=$(awk '/^name:\s*(.*)/{ print $2 }' ./*.cabal)
+packageversion=$(awk '/^version:\s*(.*)/{ print $2 }' ./*.cabal)
 
-echo -e "\033[1;36mGenerating documentation...\033[0m"
-stack haddock 2> /dev/null
+echo -e "\033[1;36mGenerating documentation for $packagename-$packageversion\033[0m"
 
-if [ "$?" -eq "0" ]; then
-  docdir=$dist/doc/html
-  cd $docdir
-  doc=$1-$2-docs
-  echo -e "Compressing documentation from \033[1;34m$docdir\033[0m for \033[1;35m$1\033[0m-\033[1;33m$2\033[1;30m"
-  cp -r $1 $doc
-  tar -c -v -z --format=ustar -f $doc.tar.gz $doc
-  echo -e "\033[1;32mUploading to Hackage...\033[0m"
-  read -p "Hackage username: " username
-  read -p "Hackage password: " -s password
-  echo ""
-  curl -X PUT -H 'Content-Type: application/x-tar' -H 'Content-Encoding: gzip' --data-binary "@$doc.tar.gz" "https://$username:$password@hackage.haskell.org/package/$1-$2/docs"
-  exit $?
-else
-  echo -e "\033[1;31mNot in a stack-powered project\033[0m"
+if ! stack haddock; then
+  echo -e "\033[1;31m'stack haddock failed, are you in a stack project?\033[0m"
+  exit 1
 fi
+
+echo "uploading docs to $packagename-$packageversion"
+docdir=$dist/doc/html
+cd "$docdir" || (echo "$docdir does not exist!"; exit 1)
+doc="$packagename-$packageversion-docs"
+echo -e "Compressing documentation from \033[1;34m$docdir\033[0m for \033[1;35m$packagename\033[0m-\033[1;33m$packageversion\033[1;30m"
+cp -r "$packagename" "$doc"
+tar -c -v -z --format=ustar -f "$doc.tar.gz" "$doc"
+echo -e "\033[1;32mUploading to Hackage...\033[0m"
+read -r -p "Hackage username: " username
+read -r -p "Hackage password: " -s password
+echo ""
+curl -X PUT -H 'Content-Type: application/x-tar' -H 'Content-Encoding: gzip' --data-binary "@$doc.tar.gz" "https://$username:$password@hackage.haskell.org/package/$packagename-$packageversion/docs" > /dev/null
+exit $?
